### ISSUE TITLE
Add a Floating "BACK/SCROLL-TO-TOP " Button

### ISSUE THREAD

**Issue by zetabug** [vikhyatsingh123/SlugTerra#112]
I have noticed that since the Slug cards on your website has increased ,the user finds it difficult to navigate back to the top midway while scrolling as the Scroll top button in your website is located at the very bottom of the site. 
So, I want to add a scroll top button with fixed position which will increase the usability of the website. I have also added a screenshot which shows a "back-to-top button" .

Please review and assign this issue to me, if it seems useful. @vikhyatsingh123  
****Hacktoberfest****
![Screenshot from 2021-10-18 23-55-50](https://user-images.githubusercontent.com/72355377/137786583-2fcee690-7576-4151-af51-905dc1669891.png)

**Comment by rudheer** [comment]
i can solve this issue, pl assign it to me
