### ISSUE TITLE
Fix line height in About section when viewed in a smaller device

### ISSUE THREAD

**Issue by zetabug** [vikhyatsingh123/SlugTerra#113]
Hey @vikhyatsingh123 
I noticed that when your website is viewed in a phone, the line height of the header in  "This Project Is Developed by Vikhyat Singh" gets messed up in the ABOUT page.

I would like to fix that,if you assign me this issue .
![Screenshot from 2021-10-19 19-36-26](https://user-images.githubusercontent.com/72355377/137927887-0dcc9019-6576-4214-ae04-858a2ebe9cee.png)

**Comment by ZMalak** [comment]
@ZMalak I have made my first pull request, thank you

**Comment by anistdnt** [comment]
@vikhyatsingh123 I can fix this so easily. Please assign me so that I can solve this problem as it is my 1st time Hacktoberfest.

**Comment by prafull904434** [comment]
sir,
may i work with this issue,
can you assign to me
