### ISSUE TITLE
Inconsistency in height of cards

### ISSUE THREAD

**Issue by Hemant1101** [vikhyatsingh123/SlugTerra#126]
There is an inconsistency in cards height , which looks bad and unprofessional, I want to work on this issue, if you can assign it to me.

**Comment by Hemant1101** [comment]
It is like this right now:

![Screenshot 2022-10-01 113832](https://user-images.githubusercontent.com/63533985/193395581-61624d1d-78df-49af-b510-9ded683d8f04.png)

My improvisation:

![Screenshot 2022-10-01 113755](https://user-images.githubusercontent.com/63533985/193395591-cfac12a8-5b97-4d52-8f5c-b77d4883a511.png)

**Comment by KedarKK1** [comment]
Assign it to me, I can resolve this issue

**Comment by vikhyatsingh123** [comment]
@Hemant1101 do it
