### ISSUE TITLE
Back  to Top Button is not working 

### ISSUE THREAD

**Issue by amey-SN** [vikhyatsingh123/SlugTerra#133]

**Comment by amey-SN** [comment]
I can fix that , please assign it to me

**Comment by Shubham-20205157** [comment]
I would like to contribute to this repo, Can you assign me this issue please.............

**Comment by Shivani1917** [comment]
Hye, can you please assign me this issue, I want to contribute to your repository

**Comment by Kedarnath-Rothe** [comment]
please assign this issue to me
