### ISSUE TITLE
There is a issue with the navbar 

### ISSUE THREAD

**Issue by amey-SN** [vikhyatsingh123/SlugTerra#134]
Before the navbar there is a unnecessary margin which looks odd

![Screenshot 2022-10-02 112524](https://user-images.githubusercontent.com/68496790/193440218-90d300fd-0c3d-4be1-91a7-a1b81f0db2af.png)

**Comment by amey-SN** [comment]
I can fix that please assign it to me

**Comment by code-genier** [comment]
Hey, @vikhyatsingh123, I would like to fix this issue, please assign this issue to me.

**Comment by codesmith25103** [comment]
@vikhyatsingh123  can you assign me this problem?

**Comment by anistdnt** [comment]
@vikhyatsingh123 I can fix this problem. Please assign this to me

**Comment by Kedarnath-Rothe** [comment]
please assign this issue to me
