### ISSUE TITLE
Improving slug cards UI

### ISSUE THREAD

**Issue by MR-DHRUV** [vikhyatsingh123/SlugTerra#144]
hey @vikhyatsingh123, I wanna improve the UI of slug cards,

**Comment by vikhyatsingh123** [comment]
Sure, kindly attach screenshots first

**Comment by MR-DHRUV** [comment]
@vikhyatsingh123 please assign this issue to me, i will be working to make cards better and all of equal height

**Comment by vikhyatsingh123** [comment]
@MR-DHRUV attach screenshots

**Comment by MR-DHRUV** [comment]
@vikhyatsingh123  I''ll be attaching them shortly
