### ISSUE TITLE
Dark Mode Feature

### ISSUE THREAD

**Issue by Mahekjain2706** [vikhyatsingh123/SlugTerra#146]
I want to add a button that will switch between dark and light modes. 
As many users prefer to view the website in dark mode for better visibility.

**Comment by Mahekjain2706** [comment]
Hey @vikhyatsingh123 , Kindly assign this task to me :)

**Comment by vikhyatsingh123** [comment]
sure!

**Comment by jainpatel25** [comment]
Can U assign this task to me?

**Comment by pallavi2031** [comment]
hey can you assign this issue I want to contribute.

**Comment by bhavyagupta-11** [comment]
Hey Can you assign this task to me?

**Comment by snehasish-pathak** [comment]
can you assign this issue to me ? 
i'll fix your issue.

**Comment by snehasish-pathak** [comment]
i can add dark mode feature

**Comment by debjitnandan05** [comment]
I want to contribute to your repository. I can add a dark mode feature to your project. Can you please assign this task to me?

**Comment by Kedarnath-Rothe** [comment]
please assign this issue to me
