### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by Utsab5** [vikhyatsingh123/SlugTerra#164]
The website is not responsive on mobile devices and i would like to work on this issue under HACKTOBERFEST :)
![sendtemp](https://user-images.githubusercontent.com/92643166/194559456-b16ca602-fb96-47f8-9ea6-2909f0b57dd1.PNG)

**Comment by Utsab5** [comment]
Thanks for assigning @vikhyatsingh123 
Can you please add the hacktoberfest labels.

**Comment by vikhyatsingh123** [comment]
already there in repo

**Comment by Utsab5** [comment]
@vikhyatsingh123 ,I was talking about this issue.
Please add the hacktober fest labels in this issue.
