### ISSUE TITLE
Modify navigation tabs for better clearance

### ISSUE THREAD

**Issue by vikhyatsingh123** [vikhyatsingh123/SlugTerra#176]

**Comment by harshvardhan614** [comment]
hi @vikhyatsingh123 can I take this issue?

**Comment by Ridham32** [comment]
hi @vikhyatsingh123 , can you assign this issue to me?

**Comment by anistdnt** [comment]
Hi @vikhyatsingh123 I am very much familier with this. Can you please assign this problem to me?

**Comment by ayushrakesh** [comment]
Hello, @vikhyatsingh123 , I am interested in this problem, can you assign this to me.

**Comment by vikhyatsingh123** [comment]
You can do that without assign
