### ISSUE TITLE
Adding footer 

### ISSUE THREAD

**Issue by AdithiDesai** [vikhyatsingh123/SlugTerra#181]
I would like to add footer to your website in which i want to add your contact links, about your website and also logo. 
Like this
![WhatsApp Image 2022-10-09 at 7 19 31 PM](https://user-images.githubusercontent.com/103984059/194760598-b8e91cd5-b699-48f5-8fed-e8673005b548.jpeg)

**Comment by harshvardhan614** [comment]
Hi @vikhyatsingh123 can I soleve this issue?

**Comment by Iamalok007** [comment]
hello sir, I want to contribute to this issue so can you please assign this to me.

**Comment by Shivani1917** [comment]
Hello sir , I want to contribute to this issue, can you please assign me !

**Comment by anistdnt** [comment]
I am very much familier with these type of problems. Please assign me for this issue.
