### ISSUE TITLE
making special hovering effect on cards in slug section

### ISSUE THREAD

**Issue by Pallavibahekar** [vikhyatsingh123/SlugTerra#186]
I will add hovering effect on them with special animation and transitions @vikhyatsingh123 
![2022-10-10 (5)](https://user-images.githubusercontent.com/97456579/194776910-7082f714-ba12-4c2c-b66e-9bf24d769a99.png)

**Comment by NiranjanLangade** [comment]
Hello There!!
I can solve this issue please assign this issue to me.

**Comment by EngineerAditijain** [comment]
Sir can you please assign this task to me

**Comment by Kedarnath-Rothe** [comment]
please assign this issue to me

**Comment by Kedarnath-Rothe** [comment]
Please see my PR and add hactoberfest-accepted label to your issue and repo

**Comment by Kedarnath-Rothe** [comment]
@vikhyatsingh123 Please see my PR
