### ISSUE TITLE
Issue with the grid of the last card added 

### ISSUE THREAD

**Issue by amey-SN** [vikhyatsingh123/SlugTerra#192]
![image](https://user-images.githubusercontent.com/68496790/194873833-c74b1d7f-75cd-4934-ac99-014437dab510.png)

**Comment by harshvardhan614** [comment]
pls assign this issue to me

**Comment by Kedarnath-Rothe** [comment]
please assign this issue to me

**Comment by vikhyatsingh123** [comment]
@Kedarnath-Rothe all these issues are fixed. you can create a new issue if you found something
