### ISSUE TITLE
Change background color and add glowing ball

### ISSUE THREAD

**Issue by RishiPratap** [vikhyatsingh123/SlugTerra#205]
<img width="893" alt="image" src="https://user-images.githubusercontent.com/72687585/195165925-ddd6e1db-4662-4edc-8527-c8c9f8288b8a.png">

similar to this

**Comment by RishiPratap** [comment]
Please assign this issue to me

**Comment by Nitish-Kamath** [comment]
Hey man can u assign this task to me :)

**Comment by rajnish254** [comment]
assign me this issue

**Comment by shubhams11-gt** [comment]
Hey there! 
can you please assign the issue to me?

**Comment by Shivani1917** [comment]
Hey, I want to contribute in this, please assign me this issue.
