### ISSUE TITLE
Add hovering affect on cards in About section

### ISSUE THREAD

**Issue by sakshi2407** [vikhyatsingh123/SlugTerra#209]
I want to improve the cards in About section by adding attractive hovering affects

**Comment by sakshi2407** [comment]
I want to work on this task. Please assign me this issue

**Comment by shubhams11-gt** [comment]
I can add hover effect with transition please assign me the task

**Comment by anistdnt** [comment]
I can add carousel and css gradient for exciting and cool look. Can you please assign this issue to me?

**Comment by moumitapodder** [comment]
i can add a beautiful neon effect on the hover section

**Comment by vikhyatsingh123** [comment]
@moumitapodder do that

**Comment by sakshi2407** [comment]
@vikhyatsingh123 Can you see my PR #232 , I've solved the issue

**Comment by Krrishn07** [comment]
Hey ! @vikhyatsingh123 I would like to do modifications for hovering effects for card and provide my contribution please assign me this.
