### ISSUE TITLE
Make Navigation tab font bold 

### ISSUE THREAD

**Issue by komalswami** [vikhyatsingh123/SlugTerra#212]
Make the Navigation tab font bold and slightly bigger. so that its experience would be clear and better.

Attaching result images

![Screenshot from 2022-10-13 10-29-43](https://user-images.githubusercontent.com/46648301/195505951-0a4d21bb-8c1a-430f-969e-34e80346a394.png)

![Screenshot from 2022-10-13 10-29-14](https://user-images.githubusercontent.com/46648301/195506000-62d8c22c-2fbb-47eb-9afe-bea3f508184a.png)

**Comment by komalswami** [comment]
Can i work on this?

**Comment by shubhams11-gt** [comment]
We can just add font-weight in CSS styling 
And i can do that for you
please assign me this task :)

**Comment by Shivani1917** [comment]
Hey, Can you please assign me this task, I want to contribute to this.
