### ISSUE TITLE
Add Elemental Slugs Data in with new Gallery

### ISSUE THREAD

**Issue by harshvardhan614** [vikhyatsingh123/SlugTerra#223]
Hey @vikhyatsingh123 , I am working on this issue. Pls, merge my PR.

**Comment by harshvardhan614** [comment]
#224 Hi, VIkhyat, Check My Pr and Merge If you like the change.

And I am working on About Page UI Design Issue. If you like the Footer And New logo in home page let me know. I will add them in About PAge.

**Comment by vikhyatsingh123** [comment]
Sure, do that
