### ISSUE TITLE
Change the style of name of slugs

### ISSUE THREAD

**Issue by vikhyatsingh123** [vikhyatsingh123/SlugTerra#244]

**Comment by Mr-krishn** [comment]
i can do this, please assign me this task

**Comment by vikhyatsingh123** [comment]
OK, attach the screenshots first

**Comment by ShailjaPatil** [comment]
Hello there!
I would like to contribute to this issue, kindly assign this issue to me.
looking forward to your reply : )

**Comment by vikhyatsingh123** [comment]
You can do that. Also attach screenshots of that. There is no need of
assign.

**Comment by ayushrakesh** [comment]
Hello sir, can I solve that problem?
Please assign it to me.

**Comment by shradham2612** [comment]
Please assign this issue to me

**Comment by Kedarnath-Rothe** [comment]
please assign this issue to me

**Comment by anshul-132002** [comment]
@vikhyatsingh123 Hey ! i want to contribute in this issue

**Comment by Kedarnath-Rothe** [comment]
@vikhyatsingh123 Please see my PR
