### ISSUE TITLE
update readme

### ISSUE THREAD

**Issue by Chanchal-D** [vikhyatsingh123/SlugTerra#336]
the readme doesn't contain the prerequisites and usage

**Comment by vikhyatsingh123** [comment]
But it will not count in hacktoberfest. It's written in hacktoberfest rule

**Comment by vikhyatsingh123** [comment]
@Chanchal-D you can pick any other issue mentioned in issues tab

**Comment by Chanchal-D** [comment]
but it is included in hacktoberfest, for non coders

**Comment by vikhyatsingh123** [comment]
ok then create PR
