### ISSUE TITLE
Fix card UI

### ISSUE THREAD

**Issue by vikhyatsingh123** [vikhyatsingh123/SlugTerra#339]
It's not looking good. Modify contributor button, hovering effect

**Comment by nitinryali** [comment]
Assign this to me

**Comment by vikhyatsingh123** [comment]
@nitinryali work on it and create PR asap

**Comment by nitinryali** [comment]
Sorry got a high priority task to do @vikhyatsingh123

**Comment by vikhyatsingh123** [comment]
so, will you work on it or not

**Comment by vikhyatsingh123** [comment]
@yashi-15 are you working on it

**Comment by yashi-15** [comment]
@vikhyatsingh123 yes.. I'll make the pull request asap.

**Comment by yashi-15** [comment]
@vikhyatsingh123  Please review and let me know for any further improvement.
