### ISSUE TITLE
Completing and Improving Abouts page.

### ISSUE THREAD

**Issue by Harsh2504** [vikhyatsingh123/SlugTerra#368]
i can contribute to these improvements:
1. I will fully improve UI of about page
2. make it evenly themed like slugterra main website 
3. Give links to your other website in it.
4. add footer too

**Comment by Sami3160** [comment]
> i can contribute to these improvements:
> 
> 1. I will fully improve UI of about page
> 2. make it evenly themed like slugterra main website
> 3. Give links to your other website in it.
> 4. add footer too

hey @vikhyatsingh123 can i work on this issue if @Harsh2504 is not working? i asked permission from him to take his issue, now only if @vikhyatsingh123 you agree, ill be happy to work on this issue.

**Comment by vikhyatsingh123** [comment]
@Harsh2504 are you working on this issue? if yes, when will you create pr? any expected time

**Comment by Harsh2504** [comment]
> @Harsh2504 are you working on this issue? if yes, when will you create pr? any expected time

No . I’m working on your other projects right now . Let him work on this issue 👍

**Comment by Sami3160** [comment]
> > @Harsh2504 are you working on this issue? if yes, when will you create pr? any expected time
> 
> No . I’m working on your other projects right now . Let him work on this issue 👍

UwU harsh-kun, arigatto Oni-chan✨

**Comment by vikhyatsingh123** [comment]
@Sami3160 you can work on this
