### ISSUE TITLE
Add Hovering Effect to cards

### ISSUE THREAD

**Issue by srivasPankhuri** [vikhyatsingh123/SlugTerra#98]
@vikhyatsingh123  I would like to add some hovering effects to the cards.
Can I do so?

**Comment by vikhyatsingh123** [comment]
It's already there. You can add animation in card when scrolling down.

**Comment by srivasPankhuri** [comment]
@vikhyatsingh123  I was talking about the hovering effects on cards. All I can see is some effects on the buttons inside the cards. Can you please check it once.

**Comment by srivasPankhuri** [comment]
Adding animations in cards alternatively will be a bit difficult since all the cards are inside a single div with class="row"

**Comment by theGDM** [comment]
Hello sir, I know I am late, but still can you please assign it to me, I really wanted to make some cool and amazing hovering effects with some nice animations.
